# Portfolio settings
title: Artists Theme
description: Dreamer // Developer // Idealist
email: artist@email

#MENU ITEM LIST

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#SKILL LIST

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Adaptable, value: '8'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '4'}
- {name: UX Design, value: '4'}
- {name: Programming, value: '4'}



# Change the site default images and content here!
logo: 'logo.svg'
bg-img: 'hero-bg.jpg'


# About Section
avatar: 'face.jpg'
blurb: <p><strong>Jose specializes in making things</strong> for human people. Most of the things he makes are well hidden projects, but he also puts effort into crafting commenting his code and watching alot of videos about making codes happen.</p>

# Work Section

projects:
- {name: Typo International, folder: 'proj-1'}
- {name: American Apparel, folder: 'proj-2'}
- {name: Crisp Icons, folder: 'proj-3'}
- {name: Typo International, folder: 'proj-4'}
- {name: Typo International, folder: 'proj-5'}
- {name: Typo International, folder: 'proj-6'}
- {name: Typo International, folder: 'proj-7'}
- {name: Typo International, folder: 'proj-8'}
