# Portfolio settings
title: Jose Santana
description: Dreamer // Developer // Idealist
email: artist@email

# NOTE: The Logo and Background image are defined in the all.sass document.

#MENU ITEM LIST

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#SKILL LIST

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Adaptable, value: '8'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '4'}
- {name: UX Design, value: '4'}
- {name: Programming, value: '4'}



# Change the site default images and content here!
logo: 'logo.svg'
background-image: 'hero-bg.jpg'


#-------------------------------
# About Section


# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Jose specializes in making things for human people. Most of the things he makes are well hidden projects, but he also puts effort into crafting commenting his code and watching alot of videos about making codes happen.

# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}
