#-------------------------------
# General Site Settings

title: Perrine Guittienne
description: Apprentie en Design Graphique
email: p.guittienne@outlook.fr

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: À Propos, url: '#about-me'}
- {name: Travaux, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+JoseASantanaJr/'
  rel-publisher: 'https://plus.google.com/u/0/+JoseASantanaJr/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **An aspiring web developer** I have over eight years of experience in the information technology field. When I think about it coming a long way and how my collective experiences helped me grown to recognize what am I truly passionate about. The great folks I met along the way, and help shape the work/life balance I'm actively pursuing to professionally help those meet a project end goal, and enjoy quality time with family and embark on travel explorations.
  As an ambitious front-end web developer, I see it as an opportunity to acquire the freedom to work remotely, especially the flexibility to be to travel and be with my loved ones more often. I always have a passion for continue learning whether related or unrelated topics to my career. An undying thirst for knowledge, especially finding creative ways to exceed any outcomes.
  Choosing this career path allows me to expand on my creativity and collaborate with others to fulfill a need, a goal, by projecting the work I'm involved with into reality.
  Currently, I'm a self-taught front-end web developer.


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Adaptable, value: '8'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '5'}
- {name: Programming, value: '5'}

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Jose was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Jose was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/JoseSantana2418'}
- {icon: 'facebook', link: 'https://www.facebook.com/jsantana2418'}
- {icon: 'github', link: 'https://github.com/jsantana2418'}
- {icon: 'google-plus', link: 'https://plus.google.com/u/0/+JoseASantanaJr/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jasantana/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
